reverting due to error in run
Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=38 Part-ID=7581384 dt=5.15425e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.66552e+20
xyz=(113.17|231.726|28.1255) tree=(1.7607e+17|-1.44107e+17|-1.67209e+17)

pm_force=(3499.58|-2903.24|-4773.95)
task 38: endrun called with an error level of 818

[cli_38]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 38

========================================================================
===========
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 6865 RUNNING AT epcc3
=   EXIT CODE: 50
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
========================================================================
===========
[proxy:0:0@epcc-head] HYD_pmcd_pmip_control_cmd_cb
(pm/pmiserv/pmip_cb.c:913): assert (!closed) failed
[proxy:0:0@epcc-head] HYDT_dmxu_poll_wait_for_event
(tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@epcc-head] main (pm/pmiserv/pmip.c:206): demux engine error
waiting for event
[proxy:0:3@epcc4] HYD_pmcd_pmip_control_cmd_cb
(pm/pmiserv/pmip_cb.c:913): assert (!closed) failed
[proxy:0:3@epcc4] HYDT_dmxu_poll_wait_for_event
(tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:3@epcc4] main (pm/pmiserv/pmip.c:206): demux engine error
waiting for event
[proxy:0:1@epcc2] HYD_pmcd_pmip_control_cmd_cb
(pm/pmiserv/pmip_cb.c:913): assert (!closed) failed
[proxy:0:1@epcc2] HYDT_dmxu_poll_wait_for_event
(tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@epcc2] main (pm/pmiserv/pmip.c:206): demux engine error
waiting for event
[mpiexec@epcc-head] HYDT_bscu_wait_for_completion
(tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated
badly; aborting
[mpiexec@epcc-head] HYDT_bsci_wait_for_completion
(tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting
for completion
[mpiexec@epcc-head] HYD_pmci_wait_for_completion
(pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for
completion
[mpiexec@epcc-head] main (ui/mpich/mpiexec.c:336): process manager
error waiting for completion