Rolled back to working version on full run
Got error at step 38 with today’s version which included changes to
declarations mainly in efforts to try to get acc errors to go away.
Rolling back to old working version (testing now on 1702 steps again
for confidence). Added acc statements that seem to be solution from
today’s investigation…

Errors before rollback:

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=9 Part-ID=7581384 dt=5.15417e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.66557e+20
xyz=(113.17|231.726|28.1255)
tree=(1.76072e+17|-1.44123e+17|-1.67208e+17)

pm_force=(3499.6|-2903.25|-4773.95)
task 9: endrun called with an error level of 818

[cli_9]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 9

========================================================================
===========
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 25252 RUNNING AT epcc-head
=   EXIT CODE: 50
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
========================================================================
===========
[proxy:0:1@epcc2] HYD_pmcd_pmip_control_cmd_cb
(pm/pmiserv/pmip_cb.c:913): assert (!closed) failed
[proxy:0:1@epcc2] HYDT_dmxu_poll_wait_for_event
(tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@epcc2] main (pm/pmiserv/pmip.c:206): demux engine error
waiting for event

(this was in effort to run a full run... 10 steps seemed to work fine
though... last step completed: 38)