Inlining creates runtime errors... :( need to fix
Errors:  (after a step or two… which go very fast)

------------------------------------------------------------------------
----------------
code termination on task=1, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=2 Part-ID=4195337 dt=0 dtc=0 dtv=0 dtdis=0.04 tibase=7.74652e-09
ti_step=0 ac=inf xyz=(62.4837|62.4735|31.172) tree=(inf|inf|inf)

pm_force=(-78.625|-214.018|-297.088)
task 2: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=3 Part-ID=10500624 dt=2.68599e-13 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=4.25809e+29
xyz=(156.228|156.329|61.5654)
tree=(5.82931e+25|8.01469e+25|-3.13926e+25)

pm_force=(-217.6|360.139|125.499)
task 3: endrun called with an error level of 818

code termination on task=4, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=5 Part-ID=4075009 dt=1.90117e-10 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=8.49933e+23
xyz=(60.6282|218.469|1.81682)
tree=(2.07463e+20|-1.58039e+18|-3.76324e+18)

pm_force=(434.455|-1174.5|-568.821)
task 5: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=6 Part-ID=2116113 dt=2.9527e-11 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=3.5236e+25
xyz=(31.3981|157.203|62.5147) tree=(3.3827e+21|3.51355e+21|7.08632e+21)

pm_force=(579.421|-136.056|-22.2789)
task 6: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=7 Part-ID=12620257 dt=1.24052e-18 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.99628e+40
xyz=(187.402|29.4375|125.968)
tree=(-5.99702e+34|4.29325e+36|2.30598e+36)

pm_force=(-423.262|587.851|-41.9727)
task 7: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=19 Part-ID=4231625 dt=6.19723e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=7.99889e+20
xyz=(62.4171|29.4205|32.0511)
tree=(-1.70144e+17|-9.10173e+16|3.00533e+16)

pm_force=(-349.384|582.573|-803.249)
task 19: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=8 Part-ID=12592641 dt=4.25194e-12 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.69923e+27
xyz=(187.55|93.5963|1.85855)
tree=(-3.77351e+23|-1.56782e+23|7.16022e+22)

pm_force=(226.601|-707.929|-310.324)
task 8: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=20 Part-ID=14687289 dt=7.26884e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=5.81426e+20
xyz=(218.634|187.318|219.695) tree=(6.4758e+16|6.71358e+16|1.07e+17)

pm_force=(-558.355|-812.99|-184.831)
task 20: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=9 Part-ID=12548640 dt=7.00505e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=6.2604e+20
xyz=(186.356|157.071|123.955)
tree=(2.15503e+16|1.29087e+17|-7.89478e+16)

pm_force=(-747.158|-493.648|-273.692)
task 9: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=21 Part-ID=4334089 dt=1.25608e-14 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.94712e+32
xyz=(64.3653|31.3728|33.007)
tree=(-4.28338e+28|-2.05995e+28|-8.35049e+26)

pm_force=(-502.278|520.525|-788.94)
task 21: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=10 Part-ID=10661393 dt=2.66517e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=4.32491e+21
xyz=(158.098|220.707|64.2678)
tree=(4.45654e+17|1.10394e+16|-9.57165e+17)

pm_force=(-406.48|65.098|-721.434)
task 10: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=22 Part-ID=2160080 dt=1.11107e-16 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=2.48854e+36
xyz=(31.2423|92.7977|61.7212)
tree=(-4.27225e+32|4.06345e+32|1.46576e+32)

pm_force=(22.1391|168.861|832.881)
task 22: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=11 Part-ID=4252121 dt=6.55153e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=7.15714e+20
xyz=(62.3464|30.4548|95.575)
tree=(-2.82743e+16|-1.47569e+17|8.91982e+16)

pm_force=(-675.033|731.246|-573.748)
task 11: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=23 Part-ID=127960 dt=5.91829e-19 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=8.77067e+40
xyz=(0.816495|61.4894|92.8547)
tree=(-1.7708e+36|5.35708e+36|2.06561e+37)

pm_force=(-573.643|-68.0423|443.898)
task 23: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=12 Part-ID=8477697 dt=3.4216e-15 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=2.62401e+33
xyz=(125.916|188.534|1.15386) tree=(4.52141e+29|4.538e+29|-6.16951e+27)

pm_force=(-277.86|222.686|689.55)
task 12: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=13 Part-ID=2189313 dt=2.66751e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=4.31732e+21
xyz=(32.2427|125.936|2.01374) tree=(4.86437e+17|1.41575e+16|9.34967e+17)

pm_force=(105.442|-193.251|262.149)
task 13: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=24 Part-ID=127440 dt=3.07964e-18 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=3.23911e+39
xyz=(0.931806|30.2258|61.539)
tree=(-5.44277e+35|5.66808e+35|-8.86201e+34)

pm_force=(-153.301|-117.824|42.6202)
task 24: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=14 Part-ID=29752 dt=3.11922e-15 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=3.15742e+33
xyz=(249.933|63.3044|217.966)
tree=(-5.31364e+29|5.54811e+29|-6.36612e+28)

pm_force=(-228.662|-800.618|799.16)
task 14: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=25 Part-ID=4283921 dt=0 dtc=0 dtv=0 dtdis=0.04 tibase=7.74652e-09
ti_step=0 ac=inf xyz=(63.3956|219.55|63.1732) tree=(inf|inf|inf)

pm_force=(-325.135|-664.608|-1140.32)
task 25: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=15 Part-ID=4195353 dt=6.07479e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=8.32458e+20
xyz=(62.4905|62.5606|93.8527) tree=(2.92481e+16|1.389e+17|1.45453e+17)

pm_force=(-208.121|293.193|454.367)
task 15: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=26 Part-ID=8373209 dt=2.03708e-18 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=7.40299e+39
xyz=(124.063|61.6416|93.9927)
tree=(-1.25897e+36|-1.29474e+36|-7.23333e+34)

pm_force=(233.705|504.861|1072.59)
task 26: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=16 Part-ID=20481 dt=4.30574e-14 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.65703e+31
xyz=(0.0640852|0.825386|1.14178)
tree=(1.0432e+27|3.84646e+27|-6.94528e+26)

pm_force=(222.975|-598.656|774.275)
task 16: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=27 Part-ID=8343073 dt=0 dtc=0 dtv=0 dtdis=0.04 tibase=7.74652e-09
ti_step=0 ac=inf xyz=(124.317|219.704|124.93)
tree=(3.21585e+38|-inf|inf)

pm_force=(1282.93|-160.686|-268.498)
task 27: endrun called with an error level of 818

code termination on task=17, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=28 Part-ID=11793 dt=2.6655e-10 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=4.32381e+23
xyz=(249.882|218.751|64.3315)
tree=(-2.50089e+19|3.48623e+19|-9.64493e+19)

pm_force=(-532.018|65.3821|-602.628)
task 28: endrun called with an error level of 818

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=18 Part-ID=8325145 dt=0 dtc=0 dtv=0 dtdis=0.04 tibase=7.74652e-09
ti_step=0 ac=inf xyz=(124.067|124.916|93.785) tree=(inf|-inf|inf)

pm_force=(189.587|-341.88|200.769)
task 18: endrun called with an error level of 818

code termination on task=29, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'
[cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 0

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=30 Part-ID=8351760 dt=1.56061e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.26136e+22
xyz=(124.121|0.902815|61.4874)
tree=(-2.24257e+18|1.20626e+16|-2.11045e+18)

pm_force=(475.58|-303.373|-312.831)
task 30: endrun called with an error level of 818

[cli_1]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=31 Part-ID=19457 dt=1.23175e-14 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=2.0248e+32
xyz=(0.128979|188.401|0.379748)
tree=(-3.49585e+28|-6.35686e+27|-3.43684e+28)

pm_force=(641.026|-410.047|1623.44)
task 31: endrun called with an error level of 818

[cli_2]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 2
code termination on task=32, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'
[cli_3]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 3
code termination on task=33, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'
[cli_4]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=34 Part-ID=8328201 dt=0 dtc=0 dtv=0 dtdis=0.04 tibase=7.74652e-09
ti_step=0 ac=inf xyz=(124.108|62.2811|32.0137)
tree=(inf|-inf|-3.1899e+37)

pm_force=(636.7|-960.719|-1022.87)
task 34: endrun called with an error level of 818

[cli_5]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 5

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=35 Part-ID=20001 dt=1.52017e-17 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=1.32935e+38
xyz=(249.696|219.59|124.937) tree=(-2.12192e+33|5.34007e+32|-3.2381e+34)

pm_force=(-1277.77|-667.795|-314.547)
task 35: endrun called with an error level of 818

[cli_6]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 6

Error: A timestep of size zero was assigned on the integer timeline!
We better stop.
Task=36 Part-ID=4329497 dt=7.27134e-09 dtc=0 dtv=0 dtdis=0.04
tibase=7.74652e-09 ti_step=0 ac=5.81027e+20
xyz=(64.2918|0.106978|94.6576)
tree=(6.57746e+16|1.06692e+17|6.64276e+16)

pm_force=(-655.63|406.218|-219.404)
task 36: endrun called with an error level of 818

[cli_7]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 7
code termination on task=37, function 'get_timestep_bin()', file
'timestep.c', line 966: 'time-step of integer size 1 not allowed
'
[cli_8]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 8
[cli_19]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 19
[cli_9]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 9
[cli_20]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 20
[cli_10]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 10
[cli_21]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 21
[cli_11]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 11
[cli_22]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 22
[cli_12]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 12
[cli_23]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 23
[cli_13]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 13
[cli_24]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 24
[cli_14]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 14
[cli_25]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 25
[cli_15]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 15
[cli_26]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 26
[cli_16]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 16
[cli_27]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 27
[cli_17]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 17
[cli_28]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 28
[cli_18]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 18
[cli_29]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 29
[cli_30]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 30
[cli_31]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 31
[cli_32]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 32
[cli_33]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 33
[cli_34]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 34
[cli_35]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 35
[cli_36]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 818) - process 36
[cli_37]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 37

========================================================================
===========
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 22052 RUNNING AT epcc2
=   EXIT CODE: 50
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
========================================================================
===========
[proxy:0:0@epcc-head] HYDU_sock_write (utils/sock/sock.c:286): write
error (Broken pipe)
[proxy:0:0@epcc-head] main (pm/pmiserv/pmip.c:265): unable to send
EXIT_STATUS command upstream